name: bonsai_abcd
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - aeon==1.2.0
      - arrow==1.4.0
      - deprecated==1.2.18
      - dotmap==1.3.30
      - harp-python
      - httpx==0.28.1
      - ipykernel==7.0.1
      - ipython==9.6.0
      - joblib==1.5.1
      - jupyterlab==4.4.10
      - llvmlite==0.44.0
      - matplotlib==3.10.5
      - numba==0.61.2
      - numpy==1.26.4
      - opencv-python==4.11.0.86
      - pandas==2.3.1
      - pillow==11.3.0
      - pynapple
      - pynwb
      - pydantic==2.12.5
      - pydantic-yaml==1.6.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - requests==2.32.5
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - setuptools==78.1.1
      - swc-aeon==0.1.0
      - threadpoolctl==3.6.0
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - wheel==0.45.1
      - wrapt==1.17.2
