name: bonsai_abcd
channels:
  - defaults
  - conda-forge
dependencies:
  - appnope=0.1.4
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - comm=0.2.3
  - debugpy=1.8.7
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.1
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=9.4.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - krb5=1.21.3
  - libcxx=17.0.6
  - libedit=3.1.20250104
  - libffi=3.4.4
  - libmpdec=4.0.0
  - libsodium=1.0.20
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.5.2
  - packaging=25.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.1
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.13.5
  - python-dateutil=2.9.0.post0
  - python_abi=3.13
  - pyzmq=26.2.0
  - readline=8.3
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tk=8.6.14
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing_extensions=4.14.1
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.2.13
  - pip:
      - aeon==1.2.0
      - attrs==25.4.0
      - colour==0.1.5
      - contourpy==1.3.3
      - cycler==0.12.1
      - deprecated==1.2.18
      - dotmap==1.3.30
      - fonttools==4.59.0
      - h5py==3.15.1
      - hdmf==4.1.2
      - imageio==2.37.2
      - ipympl==0.9.8
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - narwhals==2.11.0
      - networkx==3.5
      - numpy==1.26.4
      - opencv-python==4.11.0.86
      - pandas==2.3.1
      - path==17.1.1
      - pathlib==1.0.1
      - plotly==6.4.0
      - pynapple==0.10.1
      - pynwb==3.1.2
      - pyparsing==3.2.3
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.18
      - pyqt5-sip==12.17.2
      - pytz==2025.2
      - pyyaml==6.0.2
      - referencing==0.37.0
      - rich==14.2.0
      - rpds-py==0.28.0
      - ruamel-yaml==0.18.16
      - ruamel-yaml-clib==0.2.14
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - seaborn==0.13.2
      - swc-aeon==0.1.0
      - tabulate==0.9.0
      - tifffile==2025.10.16
      - tzdata==2025.2
      - wesanderson==0.0.4
      - wrapt==1.17.2
      - xarray==2025.10.1
